import type {
  Companion,
  CompanionTodaySchedule,
  CommunityPost,
  Conversation,
  Order,
  ServiceOffering,
} from "./types";

const future = (hours: number) => new Date(Date.now() + hours * 3_600_000).toISOString();

export const previewCompanions: Companion[] = [
  {
    id: "preview-linyu",
    name: "林予",
    role: "情绪倾听陪伴者",
    initials: "林予",
    bio: "擅长在忙乱之后，陪你把没有说完的话慢慢说清楚。不会急着给答案。",
    rating: 4.9,
    reviewCount: 126,
    isOnline: true,
    isVerified: true,
    availability: "今晚可约",
    tags: ["情绪倾听", "关系困扰"],
    specialties: ["情绪倾听", "睡前陪伴"],
    cityDistrict: "线上",
    reasonText: "与你关注的情绪倾听主题匹配",
    catalog: {
      sellable: true,
      startingPriceCents: 3900,
      startingDurationMinutes: 30,
      currency: "CNY",
      deliveryModes: ["text", "voice"],
      nextAvailableAt: future(3),
    },
  },
  {
    id: "preview-yining",
    name: "易宁",
    role: "职场减压陪伴者",
    initials: "易宁",
    bio: "做过多年团队管理，理解加班、转岗和人际消耗。陪你复盘，也尊重只是想被听见的时刻。",
    rating: 4.8,
    reviewCount: 88,
    isOnline: false,
    isVerified: true,
    availability: "明晚可约",
    tags: ["职场减压", "自我梳理"],
    specialties: ["职场减压", "成长困惑"],
    cityDistrict: "线上",
    reasonText: "近期服务稳定，明晚仍有余量",
    catalog: {
      sellable: true,
      startingPriceCents: 4900,
      startingDurationMinutes: 30,
      currency: "CNY",
      deliveryModes: ["voice"],
      nextAvailableAt: future(22),
    },
  },
  {
    id: "preview-zhixia",
    name: "知夏",
    role: "睡前陪伴者",
    initials: "知夏",
    bio: "温和、不催促，适合一天结束后聊一点轻松的小事，也可以安静陪你整理情绪。",
    rating: 4.9,
    reviewCount: 203,
    isOnline: true,
    isVerified: true,
    availability: "2 天内可约",
    tags: ["睡前陪伴", "日常分享"],
    specialties: ["睡前陪伴", "日常分享"],
    cityDistrict: "线上",
    catalog: {
      sellable: true,
      startingPriceCents: 3500,
      startingDurationMinutes: 30,
      currency: "CNY",
      deliveryModes: ["text"],
      nextAvailableAt: future(34),
    },
  },
  {
    id: "preview-moran",
    name: "莫然",
    role: "成长陪伴者",
    initials: "莫然",
    bio: "陪你面对人生选择、独处和新的开始。把复杂的感受摊开看，不评判，也不越界。",
    rating: 4.7,
    reviewCount: 61,
    isOnline: false,
    isVerified: true,
    availability: "周末可约",
    tags: ["成长困惑", "自我探索"],
    specialties: ["成长困惑", "关系困扰"],
    cityDistrict: "线上",
    catalog: {
      sellable: true,
      startingPriceCents: 5900,
      startingDurationMinutes: 45,
      currency: "CNY",
      deliveryModes: ["voice"],
      nextAvailableAt: future(74),
    },
  },
];

export const previewOfferings: Record<string, ServiceOffering[]> = Object.fromEntries(
  previewCompanions.map((companion, index) => [
    companion.id,
    [
      {
        id: `${companion.id}-text-30`,
        code: "text-30",
        title: "安静文字陪伴",
        description: "30 分钟平台内文字交流，适合慢慢说、慢慢整理。",
        deliveryMode: "text",
        durationMinutes: 30,
        priceCents: companion.catalog?.startingPriceCents ?? 3900,
        currency: "CNY",
        topicIds: companion.specialties?.slice(0, 2) ?? [],
      },
      {
        id: `${companion.id}-voice-45`,
        code: "voice-45",
        title: "专注语音陪伴",
        description: "45 分钟实时语音，服务仅在平台内完成。",
        deliveryMode: "voice",
        durationMinutes: 45,
        priceCents: (companion.catalog?.startingPriceCents ?? 3900) + 2000 + index * 200,
        currency: "CNY",
        topicIds: companion.specialties?.slice(0, 2) ?? [],
      },
    ],
  ]),
);

export const previewPosts: CommunityPost[] = [
  {
    id: "preview-post-1",
    authorId: "preview-user-1",
    authorName: "一颗青柠",
    authorInitials: "青柠",
    kind: "femaleRequest",
    topic: "下班后想找个人说说话",
    content: "最近在适应新的工作节奏，今天不太想分析原因，只希望有人耐心听一会儿。",
    likeCount: 18,
    isLiked: false,
    moderationStatus: "published",
    createdAt: future(-2),
  },
  {
    id: "preview-post-2",
    authorId: "preview-companion-1",
    authorName: "易宁",
    authorInitials: "易宁",
    companionId: "preview-yining",
    kind: "malePromotion",
    topic: "如果今天工作很累",
    content: "可以先不用急着振作。把让你疲惫的那一刻说出来，我们从那里开始。",
    likeCount: 31,
    isLiked: false,
    moderationStatus: "published",
    createdAt: future(-7),
  },
];

export const previewOrders: Order[] = [
  {
    id: "preview-order-1",
    companionId: "preview-linyu",
    themeId: "情绪倾听",
    durationMinutes: 30,
    amountCents: 3900,
    status: "paid",
    scheduledAt: future(5),
    createdAt: future(-18),
    companionSnapshot: { name: "林予", role: "情绪倾听陪伴者", initials: "林予" },
    serviceOfferingSnapshot: {
      id: "preview-linyu-text-30",
      code: "text-30",
      title: "安静文字陪伴",
      deliveryMode: "text",
      durationMinutes: 30,
      priceCents: 3900,
      currency: "CNY",
    },
  },
  {
    id: "preview-order-2",
    companionId: "preview-zhixia",
    themeId: "睡前陪伴",
    durationMinutes: 45,
    amountCents: 5500,
    status: "completed",
    scheduledAt: future(-48),
    createdAt: future(-72),
    companionSnapshot: { name: "知夏", role: "睡前陪伴者", initials: "知夏" },
    serviceOfferingSnapshot: {
      id: "preview-zhixia-voice-45",
      code: "voice-45",
      title: "专注语音陪伴",
      deliveryMode: "voice",
      durationMinutes: 45,
      priceCents: 5500,
      currency: "CNY",
    },
  },
];

export const previewConversations: Conversation[] = [
  {
    id: "preview-conversation-1",
    participant: {
      id: "preview-linyu",
      name: "林予",
      role: "companion",
      initials: "林予",
      isOnline: true,
      isVerified: true,
    },
    lastMessage: {
      id: "preview-message-1",
      content: "今晚见。如果临时需要调整，可以在订单里发起改约。",
      senderId: "preview-linyu",
      type: "text",
      timestamp: future(-1),
    },
    unreadCount: 1,
    messageNotificationsMuted: false,
    conversationBlockedByYou: false,
    messageHistoryAvailable: true,
    messageInteractionAvailable: true,
    updatedAt: future(-1),
  },
];

export const previewTodaySchedule: CompanionTodaySchedule = {
  date: new Date().toISOString().slice(0, 10),
  timezone: "Asia/Shanghai",
  pendingConfirmationCount: 2,
  items: [
    {
      id: "preview-service-1",
      scheduledAt: future(2),
      durationMinutes: 30,
      status: "pending",
      serviceTitle: "安静文字陪伴",
    },
    {
      id: "preview-service-2",
      scheduledAt: future(6),
      durationMinutes: 45,
      status: "paid",
      serviceTitle: "专注语音陪伴",
    },
  ],
};
